/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Users {
  created_at: Date | null;
  email: string;
  id: Generated<number>;
  password: string;
  updated_at: Date | null;
}

export interface DB {
  users: Users;
}
